export enum NotificationType {
  COMPETITION_STARTED = 'COMPETITION_STARTED',
  COMPETITION_INVITE = 'COMPETITION_INVITE',
  COMPETITION_WINNER = 'COMPETITION_WINNER',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  POST_LIKE = 'POST_LIKE',
  COMMENT_LIKE = 'COMMENT_LIKE',
  COMMENT_REPLY = 'COMMENT_REPLY',
  POST_COMMENT = 'POST_COMMENT',
  MENTION = 'MENTION',
  GROUP_INVITE = 'GROUP_INVITE',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
}
